services:
  azure-ai-translator:
    container_name: azure-ai-translator
    image: mcr.microsoft.com/azure-cognitive-services/translator/text-translation:latest
    environment:
        - EULA=accept
        - billing=https://aisvc-pichuang.cognitiveservices.azure.com/
        - apiKey=null
        - Languages=en,zh-Hant,zh-Hans,ja,id,es,fr,ru,en,th,fil,vi,it,pt,de,ko,tr,da,he,fa,ar,ms
        - ladurl=http://azure-ai-language:5000
        - VISIONURL=http://azure-ai-read:5000
    ports:
          - "5000:5000"
    volumes:
          - ./:/usr/local/models
  azure-ai-language:
    container_name: azure-ai-language
    image:  mcr.microsoft.com/azure-cognitive-services/textanalytics/language:latest
    environment:
      - EULA=accept
      - billing=https://aisvc-pichuang.cognitiveservices.azure.com/
      - apiKey=null
      - Languages=en,es
      - LADINCLUSTER=true
  azure-ai-read:
    container_name: azure-ai-read
    image:  mcr.microsoft.com/azure-cognitive-services/vision/read:latest
    environment:
      - EULA=accept
      - billing=https://aisvc-pichuang.cognitiveservices.azure.com/
      - apiKey=null

