services:
  nginx-healthprobe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-healthprobe
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /root/.acme.sh/echo.pichuang.com.tw_ecc/fullchain.cer:/etc/nginx/tls/fullchain.cer:ro
      - /root/.acme.sh/echo.pichuang.com.tw_ecc/echo.pichuang.com.tw.key:/etc/nginx/tls/privkey.key:ro
    security_opt:
      - no-new-privileges:false
